Feature/choose hotel
jumeneguete/drivent-front pull request #4
Opened 2021-09-06 23:14 UTC by issitarual

Conexão com o back-end e com o banco de dados da parte de escolha do hotel.

2021-09-06 23:55 UTC, vitorelourenco approved these changes

2021-09-08 17:54 UTC, thiagoribb approved these changes

2021-09-08 17:54 UTC, thiagoribb commented on src/components/Accommodation/EachHotel.js
>  export default function EachHotel({ hotelInformation }) {
Por que não só `Hotel`?

2021-09-08 17:54 UTC, thiagoribb commented on src/components/Accommodation/roomsAvailable.js
>    ];
Informações desse tipo não devem ser incluídas no projeto em produção. Semana passada foi alinhado que permitiria algo parecido apenas por conta da apresentação para o cliente.

2021-09-08 17:54 UTC, thiagoribb commented on src/components/Accommodation/index.js
> +        <SubmitRoomSelection onClick={() => alert("reservado")}>Reservar Quarto</SubmitRoomSelection>
Esse alert poderia ser substituído pelo toast que está sendo usado no projeto.

2021-09-08 17:56 UTC, thiagoribb requested changes
Os comentários acima devem ser revisados. Selecionei "Approve" sem querer.

2021-09-08 17:58 UTC, thiagoribb approved these changes

2021-09-08 18:31 UTC, merged